name: Horizon
main: xyz.hstudio.horizon.Horizon
version: '${project.version}'
api-version: '1.13'
authors:
  - MrCraftGoo
  - Anthony M.
  - Cipher
  - ExclusiveFurryYT
  - Juli_0 | Julian
  - FrozenAnarchy
softdepend:
  - PlaceholderAPI
  - ViaVersion
permissions:
  horizon.cmd.verbose:
    default: op
  horizon.cmd.analysis:
    default: op
  horizon.cmd.notify:
    default: op
  horizon.cmd.kick:
    default: op
  horizon.notify:
    default: op
  horizon.verbose:
    default: false