package xyz.hstudio.horizon.api.enums;

public enum Detection {

    AIM_ASSIST, ANTI_VELOCITY, BAD_PACKETS, FAST_BREAK, GROUND_SPOOF, HEALTH_TAG, HIT_BOX, KILL_AURA, KILL_AURA_BOT, NO_SWING, PHASE, STRAFE, VERTICAL_MOVEMENT,
}