name: Horizon
main: xyz.hstudio.horizon.Horizon
version: '${project.version}'
api-version: '1.13'
authors:
  - MrCraftGoo
  - Anthony M.
  - Cipher
  - ExclusiveFurryYT
  - Juli_0 | Julian
  - FrozenAnarchy
softdepend:
  - PlaceholderAPI
  - ViaVersion
  - ProtocolSupport
permissions:
  horizon.cmd.verbose:
    default: op
  horizon.cmd.analysis:
    default: op
  horizon.cmd.notify:
    default: op
  horizon.cmd.kick:
    default: op
  horizon.notify:
    default: op
  horizon.verbose:
    default: false
  horizon.nocancel:
    default: false
  horizon.bypass.*:
    default: false
    children:
      horizon.bypass.antibot:
        default: false
      horizon.bypass.antivelocity:
        default: false
      horizon.bypass.autoclicker:
        default: false
      horizon.bypass.badpacket:
        default: false
      horizon.bypass.groundspoof:
        default: false
      horizon.bypass.healthtag:
        default: false
      horizon.bypass.hitbox:
        default: false
      horizon.bypass.invalidmotion:
        default: false
      horizon.bypass.inventory:
        default: false
      horizon.bypass.killaura:
        default: false
      horizon.bypass.killaurabot:
        default: false
      horizon.bypass.noswing:
        default: false
      horizon.bypass.scaffold:
        default: false
      horizon.bypass.speed:
        default: false
      horizon.bypass.timer:
        default: false